# Backend (GLX é o melhor para a tua AMD)
backend = "glx";
vsync = true;

# Blur (O que nós queremos!)
blur: {
  method = "dual_kawase";
  strength = 3;

  background = true;
  background-frame = false;
  background-fixed = false;
}

# Excluir a Polybar do blur (para o texto ficar nítido)
# e outras coisas que não queremos desfocadas.

blur-background-exclude = [
  "override_redirect = true",
  "class_g = 'Polybar'",
  "class_g = 'dmenu'",
  "class_g = 'rofi'",
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "window_type = 'utility'",
  "window_type = 'notification'",
  "window_type = 'popup_menu'",
  "window_type = 'dropdown_menu'",
  "window_type = 'tooltip'",
  "window_type = 'menu'"
];

# Fading (Transições suaves ao abrir/fechar janelas)
fading = true;
fade-delta = 4;
fade-in-step = 0.027;
fade-out-step = 0.027;

# Transparência para janelas inativas (opcional, mas fixe)
inactive-opacity = 0.80;

# Transparência para o terminal (tu defines no alacritty, mas isto ajuda)
# Regra de fullscreen vem primeiro para ter prioridade: janelas em
# fullscreen ficam sempre 100% opacas, mesmo que a classe tenha uma
# regra de transparência abaixo.
opacity-rule = [
  "100:fullscreen",
  "90:class_g = 'Alacritty'" # 90% opaco para o Alacritty
];
